name: Images Action

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    name: Images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Running Image Conversion
        uses: ./
        with:
          branch: ${{ github.head_ref }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
